### ISSUE TITLE
unfortunately vagrant-1.7.4 isn't installable

### ISSUE THREAD

**Issue by oz123** [krizalys/gentoo-overlay#1]
```
yeni2gen ozn # emerge -a =app-emulation/vagrant-1.7.4

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds built with USE flags to satisfy "virtual/ruby-ssl[ruby_targets_ruby22]".
!!! One of the following packages is required to complete your request:
- virtual/ruby-ssl-6::gentoo (Missing IUSE: ruby_targets_ruby22)
(dependency required by "dev-ruby/net-ssh-3.0.1::gentoo[-test,ruby_targets_ruby22]" [ebuild])
(dependency required by "app-emulation/vagrant-1.7.4::krizalys-gentoo[ruby_targets_ruby22]" [ebuild])
(dependency required by "=app-emulation/vagrant-1.7.4" [argument])
```

**Comment by krizalys** [comment]
Thanks for the report.
I will look into it and fix it ASAP.

Meanwhile, `vagrant-bin` (also available in this overlay) should work.

**Comment by oz123** [comment]
@krizalys , I found out that if I changed the ruby target to ruby20, it would work. 
One of the dependencies for the ebuild pulls virtual-ruby/ssl-6 which has no ruby22 as a target. 

OK, I have managed to install the ebuild. I have removed all ruby versions from system which are not ruby22. Rebuild virtul-ruby/ssl-7 and the installation succeeded. 

The program will not start however. I am getting the following error:

```
vagrant 
/usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
    from /usr/lib64/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib64/ruby/gems/2.2.0/gems/vagrant-1.7.4/bin/vagrant:69:in `<top (required)>'
    from /usr/bin/vagrant:9:in `load'
    from /usr/bin/vagrant:9:in `<main>'
```
